### ISSUE TITLE
画像アップロード→編集→保存（サーバへORダウンロード）

### ISSUE THREAD

**Issue by qqhann** [enpitut2018/collatter#15]
最終的にはサーバに送る必要があるが、
ひとまず編集後のデータを画像として扱えるようになる必要があるため、
保存することを中期目標とする。

**Comment by hanpannet** [comment]
https://stackoverflow.com/questions/17692160/save-canvas-in-client-side

**Comment by qqhann** [comment]
https://www.tam-tam.co.jp/tipsnote/javascript/post13538.html
これで優勝じゃん

**Comment by qqhann** [comment]
> For security reasons, you can't set the value of a file-input element directly.
https://stackoverflow.com/questions/19032406/convert-html5-canvas-into-file-to-be-uploaded
