### ISSUE TITLE
11月7日（水）　スプリント作業日

### ISSUE THREAD

**Issue by qqhann** [enpitut2018/collatter#20]
PBIをGitHubのProjectsで管理しよう

**Comment by HaruKa-Itoi** [comment]
コラのサンプル画像を収集します

**Comment by So-shuang** [comment]
西川、はん>>編集ページへの遷移をペアプロでします。
松浦>>画像のアップロード、保存が可能に。編集ツールのスリム化をします。
鄭>>railsに組み込む方法を模索している。
糸井>>サンプルコラ画像の収集
