### ISSUE TITLE
画像編集技術の調査

### ISSUE THREAD

**Issue by hanpannet** [enpitut2018/collatter#4]
## 前提
画像編集の技術が必要。コラッターが優位性を保つには、既存サービスより優れたUXと機能が必要である。

しかしそれを実現する技術は具体的にまだわかっていないので、どんな技術で実現できるか調査が必要である。

## 現状
JavaScriptで実現できるのではないかと考えているが、確証と具体的な目処はない。
既存サービスのソースコードからどの方向性の技術を探せば良いかのヒントが得られる可能性はある。一可能性として。

**Comment by hanpannet** [comment]
@So-shuang も調査担当希望だっけ？

**Comment by yootr** [comment]
どんな技術が良いか未だに調査中です

**Comment by So-shuang** [comment]
> @So-shuang も調査担当希望だっけ？
ですです
調査中

**Comment by So-shuang** [comment]
> @So-shuang も調査担当希望だっけ？


あ

**Comment by So-shuang** [comment]
@hanpannet です。調査中

**Comment by yootr** [comment]
Drawer.js、web上で図形を描画できるjavascript
https://www.moongift.jp/2018/07/drawerjs-web%e4%b8%8a%e3%81%a7%e7%b5%84%e3%81%bf%e8%be%bc%e3%82%93%e3%81%a7%e4%bd%bf%e3%81%88%e3%82%8b%e3%83%89%e3%83%ad%e3%83%bc/

ruby,r-magickを用いて、画像に文字を描画（gravityが場所を示してる？）
https://www.mk-mode.com/octopress/2013/08/28/ruby-write-character-by-rmagick/

ruby、mini-magickを用いて画像に文字を書き込む（gravityが場所を示してる？）
http://madogiwa0124.hatenablog.com/entry/2018/07/21/170019

**Comment by yootr** [comment]
うまく行くかわからないけど構想中のやり方①
Javascriptで、GUI的な感じで座標を入手して、リアルタイムな反映をして、
r-magickかmini-magickで実際の処理を行う感じかなぁ？と思ってる。

**Comment by yootr** [comment]
r-magickやmini-magickはリアルタイムに呼び出すのは厳しそうな感じっぽいです

**Comment by yootr** [comment]
http://www.mojimaru.com/moji/

**Comment by yootr** [comment]
http://blacktails2.hatenablog.jp/entry/2014/06/22/232822

**Comment by hanpannet** [comment]
http://brianium.github.io/watermarkjs/text.html
インタラクティブな編集は見当たらないけど、手軽に文字を合成できる

**Comment by hanpannet** [comment]
URLだけじゃなくて一言でいいからどんなものか説明あるといい

**Comment by yootr** [comment]
DrawerJsを使おうと思います
https://github.com/carstenschaefer/DrawerJs

**Comment by yootr** [comment]
これがデモです（公式の）
https://carstenschaefer.github.io/DrawerJs/examples/fullscreen/

**Comment by hanpannet** [comment]
https://github.com/1j01/jspaint
一度編集位置を離れたら画像になってしまうので再度編集できない。
しかしそれは内部的な処理なので変更可能か？
