### ISSUE TITLE
Rails人材求む

### ISSUE THREAD

**Issue by hanpannet** [enpitut2018/collatter#5]
自分が時間外に動く余裕無いので、Rails人材欲しいです。

@kohei0309 に仕事振りたいけど、どういうの振っていいのかわからないので（この前DBできなぁ〜いとか言われたし）、どういうのなら振っていいのか教えて欲しいです。

**Comment by kohei0309** [comment]
DBの構成をどうすればいいのかを一緒に考えてもらいたい。
